DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: CE-IF_1
DATASET:
  datadir: /datasets
  batch_size: 32
  test_batch_size: 2048
  num_workers: 12
  imbalance_type: null
  imbalance_factor: 1
  aug_info:
    - RandomCrop
    - RandomHorizontalFlip
LOSS:
  name: CrossEntropyLoss
OPTIMIZER:
  name: SGD
  lr: 0.1
SCHEDULER:
  sched_name: cosine_annealing
  params:
    t_mult: 1
    eta_min: 0.00001
TRAIN:
  epochs: 50
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 10
  ckp_metric: bcr
  wandb:
    use: true
    entity: tootouch
    project_name: Balanced Softmax
MODEL:
  name: resnet18
  pretrained: false
